project_name: welcomi

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: welcomi
    binary: welcomi
    main: ./cmd/welcomi
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

universal_binaries:
  - replace: true

brews:
  -
    name: welcomi
    homepage: https://github.com/miyasasa/welcomi
    folder: Formula
    tap:
      owner: miyasasa
      name: homebrew-tap
    commit_author:
      name: yasin.kizilkaya
      email: vyasinw@gmail.com
