builds:
  - binary: welcomi
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    dir: .
    main: ./cmd/welcomi

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: welcomi
    homepage: https://github.com/miyasasa/welcomi
    tap:
      owner: miyasasa
      name: homebrew-tap
    commit_author:
      name: miyasasa
      email: vyasinw@gmail.com

checksum:
  name_template: 'checksums.txt'